# Generated by Django 4.0.2 on 2022-02-13 18:55

from django.db import migrations
from meals.models import Meal, Participant


def create_meals(*args):
    Meal.objects.create(
        meal_owner=Participant.objects.create(name="fantas"),
        description="pastel de papa",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0002_skip"),
    ]

    operations = [migrations.RunPython(create_meals)]
