# Generated by Django 4.0.2 on 2022-02-22 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0002_skip"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meal",
            options={"ordering": ("id",)},
        ),
    ]
