# Generated by Django 4.0.2 on 2022-03-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0003_alter_meal_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="done_at",
            field=models.DateTimeField(null=True),
        ),
    ]
