# Generated by Django 4.0.3 on 2022-04-01 03:07

from django.db import migrations


def create_items_from_meals(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Meal = apps.get_model("meals", "Meal")
    MealItem = apps.get_model("meals", "MealItem")

    MealItem.objects.bulk_create(
        [
            MealItem(meal=meal, description=meal.description, owner=meal.meal_owner)
            for meal in Meal.objects.all()
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0006_mealitem"),
    ]

    operations = [
        migrations.RunPython(create_items_from_meals, migrations.RunPython.noop)
    ]
