# Generated by Django 4.0.3 on 2022-04-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0008_remove_meal_description_remove_meal_meal_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="birthday",
            field=models.DateField(null=True),
        ),
    ]
