# Generated by Django 4.0.4 on 2022-05-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0010_birthdays"),
    ]

    operations = [
        migrations.CreateModel(
            name="CocaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reminder_hour_utc", models.PositiveSmallIntegerField()),
                ("reminder_day", models.PositiveSmallIntegerField()),
                ("history_resume_day", models.PositiveSmallIntegerField()),
                ("random_run_probability", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
